### ISSUE TITLE
FER ANÀLISI DE LA BD NECESSÀRIA PER A LA APLICACIÓ (5h)

### ISSUE THREAD

**Issue by silviadlc** [silviadlc/TripCount#2]
Crear entitats usuaris, viatges, despeses, invitacions, amistats... 
Model ER.

`01:25:25 .75`

**Comment by edusnchezj** [comment]
**ESTADO**: `Enric esta en proceso para verificarlo.`

**Comment by edusnchezj** [comment]
`Enric ha dicho que está bien las relaciones.`
